### ISSUE TITLE
Evolve the glossary generation

### ISSUE THREAD

**Issue by costezki** [OP-TED/model2owl#103]
UC big glossary: 
- Given several modules as input
- when the glossary generation is triggered
- then the output contains *one big glossary* that includes everything defined in all modules
  - class definition
  - attribute definitions
  - relation definitions
  - each item is annotated with the module where it is defined 
  - each item is annotated with the module where it is used 

Technical approaches:
- To be checked if an XMI can contain multiple models OR
- How to merge multiple XMI sources into the same processing script OR
- How to merge the outputs of the `model2owl.glossary` script

**Comment by dbd311** [comment]
This was done using the multipe xpath queries to extract the XMI structure from multiple xmi files and merge them into a single XMI.

**Comment by costezki** [comment]
The current implementation does not support merging multiple modules and processing each of them individually.
This means that generating glossary for a single module works. If we want to consider more than one module in the input then a common glossary will be generated without distinguishing the source for each class and property.


The current implementation support combined glossary without showing the source of each class or property; and generation of individual (per module) glossaries.

**Comment by costezki** [comment]
The current implementation does not support merging multiple modules and processing each of them individually.
This means that generating glossary for a single module works. If we want to consider more than one module in the input then a common glossary will be generated without distinguishing the source for each class and property.


The current implementation support combined glossary without showing the source of each class or property; and generation of individual (per module) glossaries.
