### ISSUE TITLE
NodeShape/property shape revision

### ISSUE THREAD

**Issue by costezki** [OP-TED/model2owl#106]
Make sure the current generation of node shapes with constraints on properties is correctly generated.

consider this comment from Ivo:

---
[18:37] VELITCHKOV Ivo (DIGIT-EXT)
costezki.eugen (Guest)you know, whatever you find, can you please report them on the GitHub issues?
Basically, I believe that intention was not to make a node shape but a property shape and target the objectsof the ePo property. Or:

:hasAdditionalContractNature-inScheme
  rdf:type sh:PropertyShape ;
  sh:path skos:inScheme ;
  sh:hasValue atold:Contract-nature ;
  sh:targetObjectsOf epo:hasAdditionalContractNature ;
.

[18:38] VELITCHKOV Ivo (DIGIT-EXT)
With this I'm also making another recommendation: never to use blank nodes in SHACL (I know the spec is written like that for readability but in practice that's always problematic and reduces modularity)

[18:38] VELITCHKOV Ivo (DIGIT-EXT)
If I find time I'll put some issues but I wanted just to share something I spotted now

[18:42] VELITCHKOV Ivo (DIGIT-EXT)
Depending on the orginal intention, there are four other solutions, for example
      sh:path (
          epo:hasAdditionalContractNature
          skos:inScheme
        ) ;

[18:43] VELITCHKOV Ivo (DIGIT-EXT)
But in all cases, the current shape will look in the wrong nodes to check that the right reference data is used. 
 like 1

---

**Comment by Dragos0000** [comment]
The SHACL shapes transformation rules and implementation has been changed in the new release of model2owl v2.0.0.
The new transformation rules can be found [here](https://meaningfy-ws.github.io/model2owl-docs/public-review/transformation/transf-rules2.html).
The new output can be viewed [here](https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/ePO/shacl_shapes)
