### ISSUE TITLE
change the namespace definition of "dc"

### ISSUE THREAD

**Issue by costezki** [OP-TED/model2owl#107]
currently dc is defined like so
```
xmlns:dc="http://www.omg.org/spec/UML/20131001/UMLDC"
```

we need it to be defined like so
```
xmlns:dc="http://purl.org/dc/elements/1.1/"
```

**Comment by csnyulas** [comment]
All prefixes should be in sync with the "single source of truth":
https://github.com/OP-TED/ted-rdf-conversion-pipeline/blob/main/ted_sws/resources/prefixes/prefixes.json

**Comment by dbd311** [comment]
done and will be updated in the next release
