### ISSUE TITLE
All properties with skos:Concept as range have the domain empty

### ISSUE THREAD

**Issue by dachafra** [OP-TED/model2owl#113]
Following ontology engineering good practices, the domain of properties that have `skos:Concept` as range can be detailed  (they are empty right now)

**Comment by costezki** [comment]
Not having a domain for properties derived from the "dependency connectors" seems to be a bug. 
We will investigate that.

**Comment by dbd311** [comment]
Hello, I can load the rdf file in tools like TopBraidComposer to visualize the properties with skos:Concept as range, they have at least one domain associated.

**Comment by dachafra** [comment]
is this issue properly closed?? The problem is regarding with the domain of that properties, not the range
