### ISSUE TITLE
epo:ResultNotice is defined in restrictions but not in the core

### ISSUE THREAD

**Issue by dachafra** [OP-TED/model2owl#114]
The class `epo:ResultNotice` is defined in the restrictions file but not in the core.

**Comment by costezki** [comment]
1. When the Notice is generated (this is a TED-SWS issue to be implemented), import the *core ontology* and *notice extension*. 
2. Fix the wrong namespace "http://unknown.domain/for/prefix#ResultNotice" in the generated module. This is done by augmenting the list of known/defined prefixes in the configurations file.

**Comment by andreea-pasare** [comment]
In the prefixes configuration file (https://github.com/OP-TED/model2owl/blob/master/config/ePO-default/namespaces.xml):

- "epo-ecat" is not longer needed
- "epo-not" prefix should have the vaue http://data.europa.eu/a4g/ontology#
- "core-voc" prefix should actually be "cv"

Please let me know if there are other unknown prefixes so we can handle those as well.

**Comment by costezki** [comment]
The prefix issue is fixed. The update will be reflected in the next delivery. 
The definition of epo:ResultNotice has been clarified with David.
