### ISSUE TITLE
Improvements needed to conventions_report

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#119]
Are you looking for feedback on UML Conventions Report that I'm reading at https://rawgit2.com/OP-TED/ePO/master/implementation/ePO/conventions_report/conventions_report.html ?

- "needs to conform to a set of UML conventions described elsewhere": give link
- in general, linkify every occurrence of an element being checked or referenced
- make every heading an anchor. Eg I can't provide link for "1.2 Class attribute names"
- expanding sections without count in "1.2 Class attribute names" shows nothing. It's better not to have an "expand" link at all
- the anchors for these names use only the local name, which makes them non-unique.
  - eg cccev:description generates anchor https://rawgit2.com/OP-TED/ePO/master/implementation/ePO/conventions_report/conventions_report.html#collapsedescription
- "1.3 Connector names": what do you mean by "connector", maybe "relation"?
- #class-attributes-with-multiple-usages: 
  - epo:hasAccessURL: reports different multiplicities, but doesn't give any examples
  - epo:hasAdditionalInformation: reports different definitions, when in fact they are the same

(I could write plenty more)

**Comment by andreea-pasare** [comment]
Thank you, @VladimirAlexiev! This feedback is more than welcome. We are planning to do an update for the conventions report in the near future, so we will take into consideration the comments that you provide in this ticket.

**Comment by costezki** [comment]
The suggested improvements have been implemented in the master branch. A release of the model2owl will follow in a few weeks. 

@VladimirAlexiev you can see the updated report in a “demo branch” of the EPO. 
https://htmlpreview.github.io/?https://github.com/OP-TED/ePO/blob/demo/implementation/ePO/conventions_report/conventions_report.html#uml-conventions-comformance-report

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
