### ISSUE TITLE
skos:Concept Range URI

### ISSUE THREAD

**Issue by costezki** [OP-TED/model2owl#134]
Fix the skos:Concept URI. 

![image](https://user-images.githubusercontent.com/13567133/208281928-0fa08198-80e9-4bc9-a558-d1d0c5c58354.png)

**Comment by Dragos0000** [comment]
This was fixed in the new release 2.0.0.

```:fulfillsRequirement rdfs:domain [ a owl:Class ;
            owl:unionOf ( :GreenProcurement :InnovativeProcurement :SocialProcurement ) ] ;
    rdfs:range skos:Concept .
```
