### ISSUE TITLE
bug: multiple domains and ranges

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#135]
(Maybe related to OP-TED/model2owl#136, and worse than it)

This is a serious bug in the generator:
```ttl
epo:address  rdfs:domain  dct:Location ;
        rdfs:domain  [ rdf:type     owl:Class ;
                       owl:unionOf  ( <http://www.w3.org/ns/org#Organization> <http://data.europa.eu/m8g/ContactPoint> )
                     ] ;
        rdfs:range   <http://www.w3.org/ns/locn#Address> ;
        rdfs:range   [ rdf:type     owl:Class ;
                       owl:unionOf  ( <http://www.w3.org/ns/locn#Address> )
                     ] .
```
According to RDF semantics, every triple `s epo:addres o` will lead to these inferences:
- `s` is `dct:Location` and also an anonymous type being `unionOf` two other types
- `o` is `locn:Address` and also an anonymous type being a singleton `unionOf`

**Comment by costezki** [comment]
fixed

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
