### ISSUE TITLE
Wrong namespaces for connectors that have different prefixes from epo

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#137]
In [ePO owl core file](https://github.com/OP-TED/ePO/blob/master/implementation/ePO/owl_ontology/ePO_owl_core.rdf) connectors that have prefixes different from "epo" do not have the appropriate namespace. They were attributed the epo namespace: http://data.europa.eu/a4g/ontology.

![image](https://user-images.githubusercontent.com/88081600/220886474-5d4e4011-7c8b-482b-952b-d70482235af7.png)

**Comment by costezki** [comment]
namespace definitions have been updated

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
