### ISSUE TITLE
Check that the concept URIs and document URIs follow best-practices

### ISSUE THREAD

**Issue by costezki** [OP-TED/model2owl#138]

**Comment by cristianvasquez** [comment]
The best practices patterns should be defined and documented in a SHACL document focused solely on URI patterns, this SHACL can then be used to validate such URIs

An example of a SHACL document related to URI patterns for movies:
```
@prefix sh: <http://www.w3.org/ns/shacl#> .
@prefix ex: <http://example.org/> .
ex:MovieShape a sh:NodeShape ;
    sh:targetClass ex:Movie ;
    rdfs:comment "We found that movies are entities that..." ;
    sh:property [
        sh:path sh:targetNode ;
        sh:pattern "^http://example.org/resource/movie/[a-zA-Z0-9\\-]+$" ;
        sh:message "The movie URI must start with 'http://example.org/resource/movie/' followed by alphanumeric characters or hyphens." ;
    ] ;
```

**Comment by rousso** [comment]
@cristianvasquez please add a description or delete this issue.

**Comment by cristianvasquez** [comment]
Dear @rousso, I'm not the owner of this ticket. 

Dear @costezki, should this ticket be closed?

**Comment by cristianvasquez** [comment]
Duplicated at: https://github.com/OP-TED/model2owl/issues/227
