### ISSUE TITLE
Restriction on controlled vocabularies

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#192]
Decide what to do with SHACL shapes restricted to a controlled vocabulary "class":
1. move that class definition from restriction artefact into shape artefact
2. abandon class definition and find an alternative solution in SHACL

**Comment by cristianvasquez** [comment]
Hi @andreea-pasare , could you please elaborate on the description of this issue?

**Comment by cristianvasquez** [comment]
After looking at the issue again, maybe you are referring to the elements marked as 'Enumeration' in UML. 

I would export them as follows:

Say we have a `epo:Item` that uses `a4g:hasCountryOfOrigin` to connect with one `atold:country` that in the UML is declared as an enum. If that is the case, the property in SHACL could be:

```
a4g_shape:Item-hasCountryOfOrigin-country a shacl:PropertyShape ;
	shacl:path a4g:hasCountryOfOrigin ;
	shacl:name "has country of origin"@en ;
	shacl:maxCount 1 ;
	shacl:node [
		rdf:type shacl:NodeShape ;
		shacl:property [
			shacl:path skos:inScheme ;
			shacl:hasValue atold:country ;
		] ;
	] ;
	shacl:nodeKind shacl:IRI .
```
Note that the expected value is 'something' that has `skos:inScheme` `atold:country`

There are other ways, such as specifying the elements. But this one seems straightforward

**Comment by cristianvasquez** [comment]
Maybe if such enum specify the values, say the `ex:color`, that has (in the UML) the declared values `ex:Pink` end `ex:Purple`, they might be exported using `sh:in`

```
ex:InExampleShape
	a sh:NodeShape ;
	sh:targetNode ex:RainbowPony ;
	sh:property [
		sh:path ex:color ;
		sh:in ( ex:Pink ex:Purple ) ;
	] .
```

**Comment by rousso** [comment]
@cristianvasquez Please update the description of this ticket.

**Comment by cristianvasquez** [comment]
Dear @rousso, I'm not the owner of this Github issue. 

There is another (previous) issue in Draft state

> Identify suitable representations for vocabulary restrictions: Define how these vocabulary restrictions are modelled in both SHACL and OWL. Provide examples of alternatives, such as sh:in to declare allowed values or sh:inScheme for a SKOS scheme.

The output defines how restrictions are implemented

**Comment by cristianvasquez** [comment]
duplicates: https://github.com/OP-TED/model2owl/issues/228
