### ISSUE TITLE
Modified original definitions

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#198]
Model2owl should not append any new information to the skos:definition property.
Please see examples below: 
- https://github.com/OP-TED/ePO/issues/396
- https://github.com/OP-TED/ePO/issues/397

**Comment by rousso** [comment]
@cristianvasquez this looks like a bug. Please review the description and label it as a bug if it is indeed one.

**Comment by gkostkowski** [comment]
The fix was implemented ([the change](https://github.com/OP-TED/model2owl/commit/48e04)) and will be included in the next model2owl release. 

**Solution details**

The following RDF excerpts present the change.

Former definition of a concept:
```
<rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#hasUUID">
      <skos:definition xml:lang="en">A universally unique identifier for an instance of this document. WG Approval 12/05/2020 (epo-cat:CatalogueResponseLine -&gt; adms:Identifier (+epo:hasUUID)) A universally unique identifier for an instance of this document. WG Approval 12/05/2020 (epo:Document -&gt; adms:Identifier (+epo:hasUUID))</skos:definition>
</rdf:Description>
```

New definition of a concept:
```
<rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#hasUUID">
      <skos:definition xml:lang="en">A universally unique identifier for an instance of this document. WG Approval 12/05/2020</skos:definition>
</rdf:Description>
```
