### ISSUE TITLE
Implement Tags management to enable custom properties

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#212]
Implement Tags management to enable custom properties (e.g. definitions, usage notes, alternative labels, etc.)

**Comment by cristianvasquez** [comment]
I've scoped this to handle approval notes at first step

**Comment by rousso** [comment]
@cristianvasquez Please provide a clear description for the implementer.

**Comment by cristianvasquez** [comment]
Dear @rousso, I'm not the owner of this Github Issue, 
There are issues in Draft state

> Identify key metadata:  Review and document key metadata, such as creation dates, approval notes, publication dates, and decision summaries, currently stored as comments or to be added as tags. Determine which of this metadata should be incorporated into the ontology, change logs, or other governance artefacts. Define metadata properties:  Establish how the identified metadata will be modelled in both SHACL and OWL, either by reusing existing standards or creating new properties where necessary.

It's output will define how this will be implemented

**Comment by cristianvasquez** [comment]
duplicates: https://github.com/OP-TED/model2owl/issues/229
