### ISSUE TITLE
Export of deprecated Status

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#214]
Deprecated status information is read from the metadata of Entities in the XMI, or calculated from two generated OWL/SHACL Graphs, and exported using the standard properties. How to declare an entity as deprecated needs to be exemplified in the documentation.

**Comment by cristianvasquez** [comment]
I'm adding a description:

Deprecated status information is read from the metadata of Entities in the XMI, or calculated from two generated OWL/SHACL Graphs, and exported using the standard properties. How to declare an entity as deprecated needs to be exemplified in the documentation.

**Comment by rousso** [comment]
> I'm adding a description:
> 
> Deprecated status information is read from the metadata of Entities in the XMI, or calculated from two generated OWL/SHACL Graphs, and exported using the standard properties. How to declare an entity as deprecated needs to be exemplified in the documentation.

@cristianvasquez You can edit the description field. As the owner of this backlog, please edit the description field to update the descriptions directly instead off commenting on the ticket.

Also make sure the description is clear in what is expected to be implemented and delivered as this is currently being assigned for implementation.

**Comment by cristianvasquez** [comment]
Duplicated at: https://github.com/OP-TED/model2owl/issues/230
