### ISSUE TITLE
Diffing RDF artefacts (OWL & SHACL) to generate release notes

### ISSUE THREAD

**Issue by andreea-pasare** [OP-TED/model2owl#215]

**Comment by cristianvasquez** [comment]
The diff should be ideally represented in RDF, for example with the [OWL Change Ontology](https://diegocondeherreros.github.io/OWLChangeOntology/OnToology/ontology.ttl/documentation/index-en.html)

Having this in RDF

- Is useful to automate or support the update of RML mappings to newer versions
- Impact analysis on SPARQL queries
- In case of non-conformance during RDF data validation, provide explanations to resolve the issues.
- Easy to include additional metadata about changes, such as links to GitHub issues, references to downstream systems, and other relevant context.

The release notes visualization is done through querying this RDF. 
The glossary items can point to such a change history.

**Comment by rousso** [comment]
> The diff should be ideally represented in RDF, for example with the [OWL Change Ontology](https://diegocondeherreros.github.io/OWLChangeOntology/OnToology/ontology.ttl/documentation/index-en.html)
> 
> Having this in RDF
> 
> * Is useful to automate or support the update of RML mappings to newer versions
> * Impact analysis on SPARQL queries
> * In case of non-conformance during RDF data validation, provide explanations to resolve the issues.
> * Easy to include additional metadata about changes, such as links to GitHub issues, references to downstream systems, and other relevant context.
> 
> The release notes visualization is done through querying this RDF. The glossary items can point to such a change history.

@cristianvasquez the description belongs in the description. Please move it where it belongs and check that the ticket is properly labeled.

**Comment by cristianvasquez** [comment]
@rousso , I saw you created this issue: https://github.com/OP-TED/model2owl/issues/231 . I'll close this one to not duplicate.
