### ISSUE TITLE
Multiple domain properties

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/model2owl#53]
Dear @costezki ,

when a property has multiple domain, most possibly disjoint, does the transformation artefact specifies which are these domains or it just leaves the domain restriction non-specified?

**Comment by costezki** [comment]
Dear Enric,  
Currently, both the ranges and the domains are aggregated as an anonymous class into a disjoint set. This is captured in the **restrictions.rdf** module. 

Below are two examples from ePO, first of a composite domain and second of a composite range.

```XML
<rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#hasAdditionalInformationDeadline">
      <rdfs:domain>
         <owl:Class>
            <owl:unionOf rdf:parseType="Collection">
               <rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#AccessTerm"/>
               <rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#ProcedureTerm"/>
            </owl:unionOf>
         </owl:Class>
      </rdfs:domain>
   </rdf:Description>
```

```XML
   <rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#isSubmittedBy">
      <rdfs:range>
         <owl:Class>
            <owl:unionOf rdf:parseType="Collection">
               <rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#Agent"/>
               <rdf:Description rdf:about="http://data.europa.eu/a4g/ontology#Tenderer"/>
            </owl:unionOf>
         </owl:Class>
      </rdfs:range>
   </rdf:Description>
```

**Comment by paulakeen** [comment]
Thank you, this seems correct. See also [Issue #261](https://github.com/eprocurementontology/eprocurementontology/issues/261)  in the ePO Issues Workspace.
