### ISSUE TITLE
Subproperties

### ISSUE THREAD

**Issue by paulakeen** [OP-TED/model2owl#54]
When in the UML an object property extends (or is equivalent to) another, does the transformation artefact specify the parent property of the sub-property?

**Comment by costezki** [comment]
The subproperty of is handled by the transformation script. This is available in the **core.rdf** module. 
An example of such a statement is provided below.

```XML
<owl:ObjectProperty rdf:about="http://data.europa.eu/a4g/ontology#notifies">
      <rdfs:subPropertyOf rdf:resource="http://data.europa.eu/a4g/ontology#relatesTo"/>
   </owl:ObjectProperty>
```

**Comment by paulakeen** [comment]
Good, correct, it works. See also ePO [Issue #262](https://github.com/eprocurementontology/eprocurementontology/issues/262).
