### ISSUE TITLE
CEFACT classes repeated

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/model2owl#59]
In the OWL restriction file (version at 13 November), all the CEFACT classes are repeated: one occurrence is written in first  letter upper case, the second occurrence is written in lower case with no annotations or restrictions at all defined.
Examples:
1) Amount, amount
2) Code, code
3) Identifier, identifier
4) Measure, measure
5) Quantity, quantity
6) Text, text
<img width="1200" alt="Screen Shot 2020-11-23 at 16 55 22" src="https://user-images.githubusercontent.com/24624577/99983918-c48afd00-2dac-11eb-91f0-7b3eb0226371.png">

**Comment by costezki** [comment]
this is fixed in the UML model.

**Comment by giorgialodi** [comment]
Hmmm, apart from the URi of these classes, the issue here was that they were repeated in the OWL restriction file using lowercase. T
The reason of this issue is that lowercase classes are used in many object properties. 

Examples:
we have Amount and amount defined as classes. 
hasMinimumAmount has as range the amount (lowercase) class while it should be Amount as range. The same applies for hasOverallAmount, hasMaximumAmount, 
In addition I have seen another problem here but I will open another issue apart because it is a different one.
I think this issue should be re-opened and addressed fixing the presence of these classes in lowercase. 

See the following screenshot

<img width="1139" alt="Screen Shot 2020-12-02 at 13 15 41" src="https://user-images.githubusercontent.com/24624577/100871396-84103b00-34a0-11eb-9152-fb9b6496db4e.png">

**Comment by giorgialodi** [comment]
@costezki the same thing happens for skos:Concept and skos:concept.  Look at the following screenshot:
<img width="1266" alt="Screen Shot 2020-12-03 at 09 55 42" src="https://user-images.githubusercontent.com/24624577/100986829-00ad2300-354e-11eb-89cb-ca8471464bda.png">

**Comment by giorgialodi** [comment]
I no longer see this issue.
