### ISSUE TITLE
Property "hasAvailabilityRestriction"

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/model2owl#61]
There are two properties named "hasAvailabilityRestriction": one with domain Channel and another one with domain ContactPoint.
Probably it should be one property with domain Channel or ContactPoint and range OpeningHoursSpecification

**Comment by costezki** [comment]
does this issue still persist in the new version?

**Comment by giorgialodi** [comment]
Hi Eugen, I will be able to check it as soon as the OWL files are updated at the eprocurement repository, following your latest fixes :) I will ask about that in today's call. Thanks a lot for the effort!

**Comment by giorgialodi** [comment]
I still see the issue.

So now I have a doubt: are we sure that the OWL files produced yesterday are using your latest fixes? @jseguraf 
<img width="1145" alt="Screen Shot 2020-12-02 at 13 18 42" src="https://user-images.githubusercontent.com/24624577/100871686-f5e88480-34a0-11eb-9125-36ce8f009c96.png">

**Comment by jseguraf** [comment]
Hi, 

As I said in the email, I used the latest version of the script. Before generating the OWL files, I did a pull from GitHub to be sure that I was using the latest version.

**Comment by giorgialodi** [comment]
@jseguraf I've understood this specific issue and case (the others remain a mistery wrt the doubt mentioned above!). One is written hasAvailabilityRestriction and the other one is wrongly written hasAvaliabilityRestriction.
I think the error is in the UML diagram as well. Fixing it there should be fine to really close this issue

**Comment by costezki** [comment]
Nicely spotted Giorgia. Thank you.

**Comment by jseguraf** [comment]
I already fixed the typo in v2.0.1. I will produced a new version of the OWL files after today's meeting.
