### ISSUE TITLE
Property "hasCountry"

### ISSUE THREAD

**Issue by giorgialodi** [OP-TED/model2owl#63]
The property has a domain which is "CountryIdentification or FinancialAccount" , FinancialAccount and a double range code, Country.

Probably the domain should be only "CountryIdentification or FinancialAccount"  and the range according to #60 

BTW: the CountryIdentification class is no longer available in version 2.0.2 since it did not make sense modelled as it is in version 2.0.1. We should delete it also in the OWL files for version 2.0.1. I will open an issue in the other repository.

**Comment by costezki** [comment]
related to #60
