### ISSUE TITLE
Application profile - data properties namespace

### ISSUE THREAD

**Issue by mfontsan** [OP-TED/model2owl#67]
This is related to the Application Profile:

- When in the Conceptual Model there is a class of one namespace, with data properties of another namespace. See example:
![image](https://user-images.githubusercontent.com/15996178/100844296-f91d4980-347b-11eb-93d0-2e17d7133862.png)

- When producing the restrictions, shacl and owl files, these data properties are created in the class namespace, instead of their own namespace.

For example, reg2015:AdditionalInformation is created in http://data.europa.eu/a4g/extension/ontology#hasAdditionalInformation.

The object properties are created in the expected namespace.

In case you need an example, here you have the XMI: https://github.com/eprocurementontology/eprocurementontology/tree/v2.0.1/v2.0.1/03-Analysis%20and%20design/EA-Conceptual%20Model/Reg2015-ApplicationProfile/XMI

**Comment by Dragos0000** [comment]
In the namespace definitions:
``` XML
<prefix name="epo"      value="http://data.europa.eu/a4g/ontology#" />
<prefix name="reg2015"  value="http://data.europa.eu/a4g/extension/ontology#" /> 
```
The output is as expected.
Can you please confirm that this is still an issue, and if so please explain in more detail.

**Comment by mfontsan** [comment]
You are right. 

We did not specify that this only occurs in the SHACL shapes: https://github.com/eprocurementontology/eprocurementontology/blob/v2.0.1/v2.0.1/03-Analysis%20and%20design/EA-Conceptual%20Model/Reg2015-ApplicationProfile/OWL/reg2015-owl-core.rdf

**Comment by Dragos0000** [comment]
The SHACL shapes transformation rules and implementation has been changed in the new release of model2owl v2.0.0.
The new transformation rules can be found [here](https://meaningfy-ws.github.io/model2owl-docs/public-review/transformation/transf-rules2.html).
The new output can be viewed [here](https://github.com/OP-TED/ePO/tree/v4.0.0-rc.1/implementation/ePO/shacl_shapes)
