### ISSUE TITLE
Smarter CamelCase breaking into words

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#77]
The labels for ontology terms including UPPERCASE words should be generated in a smarter way:

- xsd:AnyURI "Any u r i"@en ;
- epo:ESPDResponse  "E s p d response"@en
- cefact:hasUnitCodeListVersionID "Unit code list version i d"@en ;

**Comment by costezki** [comment]
We encountered a technical issue in XSLT that prevents us from easily detecting acronyms in strings. 
We do not intent to work on this problem in the near future again.

**Comment by rousso** [comment]
@cristianvasquez This ticket needs a better description as it is being ordered for implementation. I am reassigning this from @Dragos0000 to you so that you revise the description.

**Comment by cristianvasquez** [comment]
dear @rousso , I'm not the owner of this issue.

However, I find it quite clear. The Ontology terms including UPPERCASE words are being exported as described.

**Comment by gkostkowski** [comment]
An improved solution supporting acronyms was implemented and tested (PR #223). The change will be included in the next model2owl release.

**Solution details**
The following examples demonstrates the new behaviour. The examples present local parts of compact URIs and the generated labels:

* hasEPORole → has EPO Role
* hasVehicleID → has Vehicle ID
* hasUUID → has UUID
* ESPD → ESPD
* ESPDResponse → ESPD Response
* hasSomethingElse → has Something Else
