### ISSUE TITLE
predefined prefixes

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#78]
Some prefixes (`xsd rdf rdfs owl`, maybe `skos`) should be predefined and used.
Else eg owl-core-ePO-CM-v2.0.2-2020-11-06.rdf doesn't use `xsd:` CURIEs but full URLs, eg `<http://www.w3.org/2001/XMLSchema#Time>`

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
