### ISSUE TITLE
useless singleton unionOf

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#81]
A few props in owl-restriction-ePO-CM-v2.0.2-2020-11-06 have domains/ranges that consist of a singleton (i.e. useless) union:
```ttl
epo:isQualifiedBy  
        rdfs:range   [ a            owl:Class ;
                       owl:unionOf  ( epo:QualificationSystem )
                     ] .

epo:isReferedByA  
        rdfs:range   [ a            owl:Class ;
                       owl:unionOf  ( epo:Contract )
                     ] .

epo:isUsedToAward
        rdfs:domain  [ a            owl:Class ;
                                  owl:unionOf  ( epo:AwardCriterion )
                                ] ;
```

This is strange since many other props have normal single-class domains and ranges

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
