### ISSUE TITLE
double domain and range

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#82]
This prop in owl-restriction-ePO-CM-v2.0.2-2020-11-06 has two domains and ranges. 
```ttl
epo:hasWeightValueType
        a            owl:FunctionalProperty ;
        rdfs:domain  [ a            owl:Class ;
                       owl:unionOf  ( epo:AwardCriterion epo:SelectionCriterion )
                     ] ;
        rdfs:domain  [ a            owl:Class ;
                       owl:unionOf  ( epo:AwardCriterion epo:SelectionCriterion epo:WeightValueAwardCriterion )
                     ] ;
        rdfs:range   <http://www.unece.org/cefact#code> ;
        rdfs:range   [ a            owl:Class ;
                       owl:unionOf  ( <http://publications.europa.eu/resource/authority/Number-weight> )
                     ] .
```
I think this is a mistake since it infers the source/target of every prop instance to have 2 classes, which is probably not intended:
- `domain`: the first one is superfluous since it's subsumed by the second one
- `range`: the target node of epo:hasWeightValueType will be inferred to be both cefact:code and aut:Number-weight

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
