### ISSUE TITLE
why check for asymmetry so often?

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#84]
Most (all?) object props in owl-shapes-ePO-CM-v2.0.2-2020-11-06 have a shape check like this:
```ttl
epo:Subcontract  a        sh:NodeShape ;
        sh:sparql         [ sh:select  
""" SELECT ?this ?that WHERE 
{ ?this <http://data.europa.eu/a4g/ontology#acceptsProposalOf> ?that . 
?that <http://data.europa.eu/a4g/ontology#acceptsProposalOf> ?this .} """ ] ;
```

But the majority (all) have class restrictions, so such cyclicity is not possible or likely.
So why perform this check on every object prop?

Furthermore, epo:acceptsProposalOf is not declared owl:AsymmetricProperty in owl-restriction-ePO-CM-v2.0.2-2020-11-06 (other props are declared Asymmetric), so what's the justification for doing this check?

**Comment by costezki** [comment]
The asymmetric nature of properties is assumed by default because of a modelling decision in UML. 
Now, you nicely point out, the need to express this and I know how that can be included in the UML conventions.

**Comment by costezki** [comment]
This is defined in the association asymmetry rule R.10 and implemented accordingly.

https://meaningfy-ws.github.io/model2owl-docs/public-review/transformation/transf-rules2.html#rule:association-uni-asymetry-ds
