### ISSUE TITLE
don't repeat term & ontology metadata in shapes

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#85]
owl-shapes-ePO-CM-v2.0.2-2020-11-06 repeats a bunch of term metadata that's in owl-core-ePO-CM-v2.0.2-2020-11-06:
```ttl
        rdfs:comment      "A voluntary, deliberate, and legally binding agreement between two or more competent parties.\n\n(WG approval 01/06/2018)"@en ;
        rdfs:isDefinedBy  <http://data.europa.eu/a4g/ontology> ;
        rdfs:label        "Contract"@en ;
        sh:description    "A voluntary, deliberate, and legally binding agreement between two or more competent parties.\n\n(WG approval 01/06/2018)" ;
        sh:name           "Contract" ;
```

I think you should not do that.
Only sh:name is not repeated as a prop, but because you use the same label (minus lang tag), it is de-facto repeated and better be skipped.

Furthermore, it repeats some ontology metadata that should be skipped (it has no business of defining the VANN of another ontology):

```ttl
<http://data.europa.eu/a4g/shape>
        vann:preferredNamespacePrefix  "epo" ;
        vann:preferredNamespaceUri     "http://data.europa.eu/a4g/ontology#" ;
```

**Comment by costezki** [comment]
We have migrated to creating Node and Property shapes distinct from classes and properties. 

This issue has been addressed (is no longer relevant in the new approach) in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
