### ISSUE TITLE
omit empty, epos and epor prefixes

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#86]
The shapes and restriction ontologies define the empty prefix, which is IMHO a bad practice.
They also define derived prefixes `epos, epor` but use them only once (or not at all):

```ttl
## owl-shapes-ePO-CM-v2.0.2-2020-11-06
@prefix :      <http://data.europa.eu/a4g/shape#> .
@prefix epos:  <http://data.europa.eu/a4g/shape#> .
        owl:versionIRI                 :ePO-CM-v2.0.2-2020-11-06.eap.xmi-2020-11-07 ;

## owl-restriction-ePO-CM-v2.0.2-2020-11-06
@prefix :      <http://data.europa.eu/a4g/rule#> .
@prefix epor:  <http://data.europa.eu/a4g/rule#> .
@prefix epos:  <http://data.europa.eu/a4g/shape#> .
        owl:versionIRI                 epor:ePO-CM-v2.0.2-2020-11-06.eap.xmi-2020-11-07 ;
```

Please omit all these prefixes, and just emit a full URL in owl:versionIRI.

WHY: many repos (including GraphDB) remember ingested prefixes as "namespaces" (there are rdf4j calls to handle namespaces), so you should avoid namespace pollution.

**Comment by costezki** [comment]
We still keep the based prefix of the overall ontology and the default prefix consistently, everywhere. But all other ones are now properly defined. 

This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
