### ISSUE TITLE
reduce imports

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#87]
owl:import is by no means free, so please omit imports that you don't need.
You can use terms of an ontology without importing it!
You need to import only if you need inference from the imported ontology.

```ttl
<http://data.europa.eu/a4g/shape> owl:imports
  <http://www.w3.org/2004/02/skos/core> , # NOT used
  <http://datashapes.org/dash> , # NOT used
  dct: , # NOT needed, only dct:date used
  <http://data.europa.eu/a4g/ontology> , # MAYBE is needed
  sh: ; # many terms used but no inference is needed
```

**Comment by dbd311** [comment]
Hi,

We have a mechanism to import only useful imports.

This will be fixed in the next release.
