### ISSUE TITLE
useless restrictions

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#89]
owl-restriction-ePO-CM-v2.0.2-2020-11-06 includes some restrictions that are useless because they don't really restrict anything:
```ttl
epo:AccessTerm  a        owl:Class ;
        rdfs:subClassOf  [ a               owl:Restriction ;
                           owl:onProperty  epo:hasRestrictedProcurementDocumentsMadeAvailableVia
                         ] ;
```

Also, the prop definition already says more:
```
epo:hasRestrictedProcurementDocumentsMadeAvailableVia
        rdfs:domain  epo:AccessTerm ;
        rdfs:range   epo:Channel .
```

And this restriction:
```ttl
epo:Agent  a             owl:Class ;
        rdfs:subClassOf  [ a                   owl:Restriction ;
                           owl:maxCardinality  1 ;
                           owl:onProperty      epo:usesBuyerProfile
                         ] ;
epo:usesBuyerProfile  rdfs:domain  epo:Agent ;
        rdfs:range   epo:BuyerProfile .
```
is better (more simply) represented as

```ttl
epo:usesBuyerProfile  a owl:FunctionalProperty
        rdfs:domain  epo:Agent ;
        rdfs:range   epo:BuyerProfile .
```

You use owl:FunctionalProperty on other props, so why not here?

**Comment by costezki** [comment]
They seem to come from different transformation rules, that is the reason. 
Still, need to check those rules again.

**Comment by dbd311** [comment]
Hello, it looks like that the examples were outdated. We cannot re-produce the examples since the data was too old.

Can you please provide an example with the latest input / output data?

**Comment by VladimirAlexiev** [comment]
hi @dbd311 Can you give link to the latest output?

**Comment by costezki** [comment]
This issue has been addressed in *model2owl*. 
Please refer to the latest transformation of *eProcurement Ontology* available in this branch:
https://github.com/OP-TED/ePO/tree/demo/implementation.
