### ISSUE TITLE
prefix `dc` is confusing

### ISSUE THREAD

**Issue by VladimirAlexiev** [OP-TED/model2owl#92]
```
@prefix dc:    <http://www.omg.org/spec/UML/20131001/UMLDC> .
@prefix dct:   <http://purl.org/dc/terms/> .
```
But everyone knows that `dc:` means the following (see https://prefix.cc/dc.ttl):
```
@prefix dc: <http://purl.org/dc/elements/1.1/>.
```

Either correct or remove this prefix (which is not used anyway)

**Comment by dbd311** [comment]
This will be fixed in the next release.
